name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.9', '3.13']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Install conda environment
      run: |
        sed -i 's/python=3.9/python=${{ matrix.python-version }}/' environment.yml
        conda env create -n run-preflight -f environment.yml

    - name: Test with pytest
      run: |
        conda activate run-preflight
        pytest

    - name: Lint with ruff
      run: |
        conda activate run-preflight
        ruff check . --statistics
